# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 642443ad00ce149734aadcac8db69d0d45e1fdb3f2e5753bdad38883187d21395933661fb264a647ad99d07614f90f1d1c9046bae9c0aca344165d78c4ab7328

test:
  secret_key_base: 71399ded54768a0eed6f7af660c74c384318278d495f00dd6d78d6e381f3f0831fb6af1c85d03fc5b4118279327bbe00bb5ca4099dd6ae302b1ae7cb3225a2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
